theme: jekyll-theme-leap-day

title: "Innovations and Opportunities in<br>Liberal Arts Computing Education"
description: "SIGCSE 2021 Pre-Symposium Event by the SIGCSE Committee on Computing Education in Liberal Arts Colleges"
